### ISSUE TITLE
field.name reports same value as field.caption

### ISSUE THREAD

**Issue by intrasight** [tableau/document-api-python#192]
My table has a column "OffsetClass". I see in the xml of my workbook:

`      <column caption='Offset Class' datatype='string' name='[OffsetClass]' role='dimension' type='nominal' />
`

and I would assume that field.name would return the value "[OffsetClass]" but instead I get "Offset Class".

How can I get the table column name?

My code:

```
sourceWB = Workbook('MyWorkbook.twb')

worksheets = sourceWB.worksheets

print("worksheet, count, name, datatype, caption, aggregation, description, calculation")

for worksheet in worksheets:

    for datasource in sourceWB.datasources:

        for count, field in enumerate(datasource.fields.values()):

            for fieldWorksheet in field.worksheets:

                if worksheet == fieldWorksheet:

                    print(worksheet, ",", count, ",", field.name, ",", field.datatype, ",", field.caption, ",", field.default_aggregation, ",", field.description)
```

**Comment by jacalata** [comment]
Probably too late to be useful, but for posterity: The attribute labelled "name" in the xml is available as the "id" of a field object. This is because you can set the displayed name elsewhere. 
field.name is calculated as
1)  the alias 
or 2) the caption if alias is not defined,
or 3) the id (which is the underlying name in xml) if neither caption or alias exist. 

alias = Name of the field as displayed in Tableau if the default name isn't wanted 
caption =  Default name of the field as displayed in Tableau
id = Name of the field as specified in the xml file, usually surrounded by [ ]
