### ISSUE TITLE
released version 0.8 not pushed to Pypi

### ISSUE THREAD

**Issue by rchevallier** [tableau/document-api-python#213]
as title said.

**Comment by dev-mkc19** [comment]
@jacalata if go deeper we will see that 1 test failed for pypy.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/10463072/139853888-1ac98b48-de60-4fc6-896b-76f0b41cddd1.png">

**Comment by dev-mkc19** [comment]
@jacalata Can you help with this?

**Comment by jacalata** [comment]
sorry, thought someone else had done this. The problem is that pypy == python 2, I'm a little surprised this is the only failure that showed up. I think we're about at the stage where we can ditch the Travis CI for Github builds, but for now I've just edited the config to use pypy3. 
Now we should be able to publish to pypi.

**Comment by bryceglarsen** [comment]
Thanks for updating, @jacalata ! Do we know when this should get pushed to pypi?

**Comment by bryceglarsen** [comment]
Just wanted to follow-up on this. 🙏

**Comment by mmuttreja-tableau** [comment]
Hi, can you use v0.9 https://pypi.org/project/tableaudocumentapi/0.9/ ?
