### ISSUE TITLE
Identify which fields are "in use" in a workbook

### ISSUE THREAD

**Issue by t8y8** [tableau/document-api-python#47]
- On row or columns shelf
- In use as a filter
- On any level of detail (Size, Shape, Color, LOD)

Possibly others

**Comment by RussTheAerialist** [comment]
Quick question about API here.

My initial implementation added a "usedFields" to the datasource, but that seems a bit wrong now that I look at it because the concept of "in use" is really not tied to the datasource, it's more tied to the workbook.

Originally I wanted to have an in_use property on the Field object, but again, that feels wrong because the field isn't really "in use" it's more that the worksheet is using the field (circular, I know).

I'm thinking about putting a method on the workbook called something like field_in_use_by('datasource_name') or something similar that would give you a dictionary of only the fields that are in use from that datasource.

**Comment by t8y8** [comment]
Yeah, the design here will be the tricky part.

Really, it's a property of a specific viz/sheet/view, and not necessarily the entire workbook, but I'm not sure we want to go down that rabbit hole yet.

fields_in_use_by() could take a datasource object, since we don't really return names anywhere, and names are poorly defined (they're autogenerated usually).

I think I'd need to play with it to really get a feel for the API. I'll think on it more...
